name:  Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
 

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          SECTION: activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
